# frontend/Dockerfile
FROM node:20  
# 👈 Cambiado de node:20-alpine a node:20

# Instalar pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copiar solo lo necesario para instalar dependencias
COPY package.json pnpm-lock.yaml ./

# Instalar dependencias
RUN pnpm install --frozen-lockfile

# Copiar el resto del código
COPY . .

EXPOSE 5173

CMD ["pnpm", "run", "dev"]